#ifndef __OPTIONS_H__
#define __OPTIONS_H__

#define OPTION_AUTOAPPROVE                      "autoapprove"
#define OPTION_AUTOAWAY                         "autoaway"
#define OPTION_BOARDALIGNTOP                    "boardaligntop"
#define OPTION_BOARDSIZE                        "boardsize"
#define OPTION_DISCONNECTONLOGOUT               "disconnectonlogout"
#define OPTION_HIDEPARTICIPANTS                 "hideparticipants"
#define OPTION_HIDEPENDING                      "hidepending"
#define OPTION_HIDEWELCOMEDIALOG                "hidewelcomedialog"
#define OPTION_NEWLINEONSHIFT                   "newlineonshift"
#define OPTION_NOCHATNOTIFY                     "nochatnotify"
#define OPTION_NOGAMENOTIFY                     "nogamenotify"
#define OPTION_NOINITIALROSTER                  "noinitialroster"
#define OPTION_SHOWAVATARS                      "showavatars"
#define OPTION_SHOWMUCPRESENCEINCHAT            "showmucpresenceinchat"
#define OPTION_SHOWMUCPRESENCEINCHATWHENCLOSED  "showmucpresenceinchatwhenclosed"
#define OPTION_SHOWOFFLINE                      "showoffline"
#define OPTION_NOGAMEAUTOFLAG                   "nogameautoflag"
#define OPTION_HIDEFRIENDSTAB                   "hidefriendstab"
#define OPTION_HIDEROOMSTAB                     "hideroomstab"
#define OPTION_HIDEGAMESTAB                     "hidegamestab"
#define OPTION_SHOWFRIENDGROUPS                 "showfriendgroups"
#define OPTION_DISABLEANIMATION			"disableanimation"
/*#define OPTION_DISABLELAGCOMPENSATION		"disablelagcompensation"*/
#define OPTION_ENABLELAGHIDING                  "enablelaghiding"
#define OPTION_DISABLESOUNDS			"disablesounds"
#define OPTION_DISABLEIMSOUNDS                  "disableimsounds"
#define OPTION_INITIALIMSOUNDONLY               "initialimsoundonly"
#define OPTION_VOLUME                           "volume"
#define OPTION_NOGAMESEARCHONLOGIN              "nogamesearchonlogin"
#define OPTION_DEVFEATURES                      "devfeatures"
#define OPTION_TABNEWCHATS                      "tabnewchats"
#define OPTION_ENABLECHATMERGING                "enablechatmerging"
/*#define OPTION_ENABLEPUSHADS                    "enablepushads"*/
#define OPTION_MESSAGEONAWAY                    "messageonaway"
#define OPTION_PERLINECHATTIMESTAMPS            "perlinechattimestamps"
#define OPTION_ENABLEANTISLIP                   "enableantislip"
#define OPTION_SEARCHFILTERS                    "searchfilters"
#define OPTION_HIDEGAMEFINDERHELP               "hidegamefinderhelp"
#define OPTION_HIDEWARNINGONDISCONNECT          "hidewarningondisconnect"
#define OPTION_DISABLEPROFANITYFILTER           "disableprofanityfilter"
/*#define OPTION_MODERATORFEATURES                "moderatorfeatures"*/
#define OPTION_DISABLEROSTERGAMENOTIFICATIONS   "disablerostergamenotifications"
#define OPTION_NODECLINEWHENAWAY                "nodeclinewhenaway"
#define OPTION_HIDEWARNINGONDISCONNECT          "hidewarningondisconnect"
#define OPTION_NOTIFICATIONTIME                 "notificationtime"
#define OPTION_NOTIFICATIONLOCATION             "notificationlocation"
#define OPTION_HIDEVARIANTWARNING               "hidevariantwarning"
#define OPTION_GAMECHATONBOTTOM                 "gamechatonbottom"
#define OPTION_GAMECHATPARTICIPANTSONTOP        "gamechatparticipantsontop"
#define OPTION_LOGINROOMS			"loginrooms"
#define OPTION_LOWBANDWIDTH			"lowbandwidth"
#define OPTION_SHOWLEGALMOVES			"showlegalmoves"
#define OPTION_DISABLEGAMESOUNDS                "disablegamesounds"
#define OPTION_PIECESTHEME                      "pieces-theme"

struct Box_s *Options_Create(struct Box_s *roster);

#endif
